### PR TITLE
Removed lib/ since we dont work in lib folder

### PR DESCRIPTION
**Pull request by rickerd**

### CODE REVIEW

**Comment by KuroNeko-san** [comment]
Or we can create /lib/. Can it be more right way?

**Comment by rickerd** [comment]
Yes for me it looks better.
I'm planning to take the library apart and remove all the duplicate code from the wsdl stuff and soap headers.

Now the connection and response is in 1 library and that doesnt feel good.
Do you want to help? Im also transforming it to php6 standards with new array syntaxis.
(I dont use the method hinting btw)

**Comment by KuroNeko-san** [comment]
For now i can't work on this library. If you can develop it - do it.
My task was to implement WS-Discovery.

**Comment by KuroNeko-san** [comment]
/lib/ folder created.

**Comment by rickerd** [comment]
Can you add me as a collaborator?
Then i can add the package to packgist and make the repo better.
I will still use branches and PR to merge to master.

**Comment by KuroNeko-san** [comment]
Sure.

**Pull request closed without merging**
